//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wuyu.Epub.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wuyu.Epub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;container version=&quot;1.0&quot; xmlns=&quot;urn:oasis:names:tc:opendocument:xmlns:container&quot;&gt;
        ///   &lt;rootfiles&gt;
        ///      &lt;rootfile full-path=&quot;{0}&quot; media-type=&quot;application/oebps-package+xml&quot;/&gt;
        ///   &lt;/rootfiles&gt;
        ///&lt;/container&gt; 的本地化字符串。
        /// </summary>
        internal static string container {
            get {
                return ResourceManager.GetString("container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE html&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;zh-CN&quot; xmlns:epub=&quot;http://www.idpf.org/2007/ops&quot; xmlns:xml=&quot;http://www.w3.org/XML/1998/namespace&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;link href=&quot;../Styles/style.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot;/&gt;
        ///  &lt;title&gt;封面&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;div class=&quot;cover duokan-image-single&quot;&gt;
        ///    &lt;img alt=&quot;cover&quot; src=&quot;{0}&quot;/&gt;
        ///  &lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string cover {
            get {
                return ResourceManager.GetString("cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE html&gt;
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:epub=&quot;http://www.idpf.org/2007/ops&quot; lang=&quot;zh-CN&quot; xml:lang=&quot;zh-CN&quot;&gt;  
        ///  &lt;head&gt; 
        ///    &lt;title&gt;目录&lt;/title&gt; 
        ///  &lt;/head&gt;  
        ///  &lt;body epub:type=&quot;frontmatter&quot;&gt; 
        ///    &lt;nav epub:type=&quot;toc&quot; id=&quot;toc&quot;&gt;
        ///      &lt;h1&gt;CONTENTS&lt;/h1&gt;  
        ///      &lt;ol/&gt;
        ///    &lt;/nav&gt;  
        ///    &lt;nav epub:type=&quot;landmarks&quot; id=&quot;guide&quot;&gt; 
        ///      &lt;h1&gt;Guide&lt;/h1&gt;  
        ///      &lt;ol&gt;&lt;/ol&gt; 
        ///    &lt;/nav&gt; 
        ///  &lt;/body&gt; 
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string nav {
            get {
                return ResourceManager.GetString("nav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;nav xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xmlns:epub=&quot;http://www.idpf.org/2007/ops&quot; epub:type=&quot;landmarks&quot; id=&quot;guide&quot;&gt;
        ///&lt;h1&gt;Guide&lt;/h1&gt;
        ///&lt;ol&gt;
        ///
        ///&lt;/ol&gt;
        ///&lt;/nav&gt; 的本地化字符串。
        /// </summary>
        internal static string navGuideCover {
            get {
                return ResourceManager.GetString("navGuideCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;package version=&quot;3.0&quot; unique-identifier=&quot;BookId&quot; xmlns=&quot;http://www.idpf.org/2007/opf&quot;&gt;
        ///  &lt;metadata xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;&gt;
        ///    &lt;dc:language&gt;zh-CN&lt;/dc:language&gt;
        ///    &lt;dc:title&gt;[此处填写主标题]&lt;/dc:title&gt;
        ///  &lt;/metadata&gt;
        ///  &lt;manifest&gt;
        ///  &lt;/manifest&gt;
        ///  &lt;spine&gt;
        ///  &lt;/spine&gt;
        ///&lt;/package&gt; 的本地化字符串。
        /// </summary>
        internal static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
    }
}
